# Generated by Django 5.2 on 2025-05-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_type', models.CharField(max_length=50)),
                ('target_audience', models.CharField(max_length=50)),
                ('seasonality', models.CharField(max_length=50)),
                ('preferred_channels', models.CharField(max_length=200)),
                ('primary_interest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_budget_allocation', models.TextField()),
                ('expected_leads', models.IntegerField()),
                ('estimated_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.userinputs')),
            ],
        ),
    ]
