# Generated by Django 5.2 on 2025-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_userinputs_modeloutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloutputs',
            name='estimated_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userinputs',
            name='total_budget',
            field=models.FloatField(),
        ),
    ]
