# Generated by Django 5.2 on 2025-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_modeloutputs_estimated_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloutputs',
            name='channel_effectiveness',
            field=models.TextField(default='{}'),
        ),
    ]
