# Generated by Django 5.2 on 2025-05-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_modeloutputs_channel_effectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloutputs',
            name='estimated_channel_revenue',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='modeloutputs',
            name='most_effective_channel',
            field=models.JSONField(default={}),
        ),
    ]
