# Generated by Django 5.2 on 2025-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_modeloutputs_estimated_channel_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloutputs',
            name='most_effective_channel',
            field=models.JSONField(default=dict),
        ),
    ]
