# Generated by Django 5.2 on 2025-05-24 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_alter_modeloutputs_most_effective_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloutputs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
